name: GitHub Metrics Helper
on:
  workflow_call:
    inputs:
      plugin_introduction:
        description: 'A plugin_introduction passed from the caller workflow'
        default: yes
        required: false
        type: string
          # https://github.com/lowlighter/metrics/blob/master/source/plugins/achievements/README.md
      plugin_achievements:  
        description: 'A plugin_achievements passed from the caller workflow'
        default: no
        required: false
        type: string       
    secrets:
      token:
        required: true

  # Schedule at 00:00 on every 3rd day-of-month, https://crontab.guru/#0_0_*/3_*_*
  #schedule: [{ cron: "0 0 */3 * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on main
  #push: { branches: ["main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set Current Year
        id: set-current-year
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
        run: |
          echo "Setting current year from: $(date), current system clock time: \n$(timedatectl)"
          echo "CURRENT_YEAR=$(date +'%Y')" >> "$GITHUB_OUTPUT"
      # https://github.com/lowlighter/metrics/blob/master/.github/readme/partials/documentation/setup/action.md
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-myintro5.svg
          token: ${{ secrets.token }}
          user: vadimdor
          # https://github.com/lowlighter/metrics/blob/master/source/plugins/core/README.md#using-gists
          output_action: gist
          committer_gist: efedf3c3dc5c472c3103caaa15db68a0
         # committer_message: "chore($metrics): update GitHub metrics via GitHub Actions"
          template: classic
          config_timezone: Europe/Paris
          base: header, activity, community, repositories, metadata
          
          plugin_introduction: ${{ inputs.plugin_introduction }}
          
          # https://github.com/lowlighter/metrics/blob/master/source/plugins/achievements/README.md
          plugin_achievements:  ${{ inputs.plugin_achievements }}
          plugin_achievements_threshold: C
          plugin_achievements_display: compact
